# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
get_kgram_freqsC <- function(sentences, dict, N) {
    .Call(`_sbo_get_kgram_freqsC`, sentences, dict, N)
}

#' @export
get_word_freqsC <- function(text) {
    .Call(`_sbo_get_word_freqsC`, text)
}

#' @export
preprocess <- function(lines) {
    .Call(`_sbo_preprocess`, lines)
}

