# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_kgram_freqsC <- function(sentences, dict, N) {
    .Call(`_sbo_get_kgram_freqsC`, sentences, dict, N)
}

get_word_freqsC <- function(text) {
    .Call(`_sbo_get_word_freqsC`, text)
}

predict_sbo_preds <- function(object, input) {
    .Call(`_sbo_predict_sbo_preds`, object, input)
}

#' @export
preprocess <- function(input, erase = "[^.?!:;'\\w\\s]", lower_case = TRUE) {
    .Call(`_sbo_preprocess`, input, erase, lower_case)
}

#' @export
tokenize_sentences <- function(input, EOS = ".?!:;") {
    .Call(`_sbo_tokenize_sentences`, input, EOS)
}

